### PR TITLE
replace deprecated Buffer constructor

### PR DESCRIPTION
**Pull request by gabrielschulhof**
Fixes: https://github.com/dominictarr/json-buffer/issues/9

### CODE REVIEW

**Comment by dominictarr** [comment]
merged into 3.0.1

**Comment by dominictarr** [comment]
oh I thought this was the other thing with `new Buffer(number)` which was a security thing. new `Buffer(string)` may be depreciated but they'll never actually remove it, because it would break too much stuff. I've merged this, but I'm not interested in making this trivial change to any other modules. (although changing `new Buffer(number)` to `Buffer.alloc(number)` is okay) there are just too many instances where I have done this and I have better things to do with my time.

**Comment by dominictarr** [comment]
I feel I should give a little more context: I have hundreds of modules, many that are used in various other things, but that I no longer use my self. I don't get anything out of maintaining them, it's not exciting to work on them anymore, and neither is there any financial reward. This is not a personal feedback on anyone, I'm just not motivated to maintain these modules anymore. This is an unsatisfying state of affairs for everyone, users of these modules and my self, but that is the situation that the state of the tools leaves us in.

**Comment by gabrielschulhof** [comment]
@dominictarr this has been a fairly systematic PR. Basically,

```sh
git grep -nH 'new Buffer' | \
  awk -F ':' '{print $1;}' | \
  sort -u | \
  while read; do \
    sed -i"" -r "s/new Buffer[(]([^,'\"[]+)[)]/Buffer.alloc(\\1)/" "$REPLY" && \
    sed -i"" 's/new Buffer(/Buffer.from(/g' "$REPLY" ; \
  done
```

... and then going through the git diff by hand because it sometimes replaces with `Buffer.alloc(...)` when it should be replacing with `Buffer.from(...)`.

If I run into any other modules that need this change, I will submit a similarly systematic PR.

**Comment by dominictarr** [comment]
yeah, I know it's trivial that is the point, it still takes ten minutes to do email, checkout clone, npm pub etc etc. it's just a waste of my time. please _don't_ submit a PR. I guess if it's really important your company can contract me to look at this stuff. otherwise I'd rather ignore this stuff. This is not a reflection on you or anything like this, I just don't care about this stuff anymore, but unfortunately there is no easy way to put these modules up for adoption (in bulk) or similar.

**Comment by gabrielschulhof** [comment]
@dominictarr OK, I understand.

**Pull request merged**
